apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eosc-service-registry.fullname" . }}
  labels:
    {{- include "eosc-service-registry.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_43=No need for image digest
    checkov.io/skip2: CKV_K8S_42=No read-only fs
    checkov.io/skip3: CKV_K8S_15=Image pull policy is set elsewhere
    checkov.io/skip4: CKV_K8S_21=Namespace is set elsewhere
    checkov.io/skip5: CKV_K8S_29=Security Context is set elsewhere
    checkov.io/skip6: CKV_K8S_40=We are already using non root
    checkov.io/skip7: CKV_K8S_6=We are already using non root
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eosc-service-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eosc-service-registry.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.imageCredentials.username }}
      imagePullSecrets:
        - name: eosc-registry-pullsecrets
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
