[project]
name = "eosc-service-catalogue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Enol Fernández", email = "enol.fernandez@egi.eu" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.138.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
eosc-service-catalogue = "eosc_service_catalogue:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "eosc_service_catalogue.main:app"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pytest>=9.1.0",
    "pytest-cov>=7.1.0",
]
