"""Common fields for every model version"""

# generated by datamodel-codegen:
#   filename:  eosc_service_catalogue.schema_v3.json
#   timestamp: 2026-05-08T10:47:24+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field


class LanguageCode(Enum):
    aa = "aa"
    ab = "ab"
    ae = "ae"
    af = "af"
    ak = "ak"
    am = "am"
    an = "an"
    ar = "ar"
    as_ = "as"
    av = "av"
    ay = "ay"
    az = "az"
    ba = "ba"
    be = "be"
    bg = "bg"
    bh = "bh"
    bi = "bi"
    bm = "bm"
    bn = "bn"
    bo = "bo"
    br = "br"
    bs = "bs"
    ca = "ca"
    ce = "ce"
    ch = "ch"
    co = "co"
    cr = "cr"
    cs = "cs"
    cu = "cu"
    cv = "cv"
    cy = "cy"
    da = "da"
    de = "de"
    dv = "dv"
    dz = "dz"
    ee = "ee"
    el = "el"
    en = "en"
    eo = "eo"
    es = "es"
    et = "et"
    eu = "eu"
    fa = "fa"
    ff = "ff"
    fi = "fi"
    fj = "fj"
    fo = "fo"  # codespell:ignore
    fr = "fr"
    fy = "fy"
    ga = "ga"
    gd = "gd"
    gl = "gl"
    gn = "gn"
    gu = "gu"
    gv = "gv"
    ha = "ha"
    he = "he"
    hi = "hi"
    ho = "ho"
    hr = "hr"
    ht = "ht"
    hu = "hu"
    hy = "hy"
    hz = "hz"
    ia = "ia"
    id = "id"
    ie = "ie"
    ig = "ig"
    ii = "ii"
    iii = "iii"
    ik = "ik"
    io = "io"
    is_ = "is"
    it = "it"
    iu = "iu"
    ja = "ja"
    jv = "jv"
    ka = "ka"
    kg = "kg"
    ki = "ki"
    kj = "kj"
    kk = "kk"
    kl = "kl"
    km = "km"
    kn = "kn"
    ko = "ko"
    kr = "kr"
    ks = "ks"
    ku = "ku"
    kv = "kv"
    kw = "kw"
    ky = "ky"
    la = "la"
    lb = "lb"
    li = "li"
    ln = "ln"
    lo = "lo"
    lt = "lt"
    lu = "lu"
    lv = "lv"
    mg = "mg"
    mh = "mh"
    mi = "mi"
    mk = "mk"
    ml = "ml"
    mn = "mn"
    mr = "mr"
    ms = "ms"
    mt = "mt"
    my = "my"
    na = "na"
    nb = "nb"
    nd = "nd"  # codespell:ignore
    ne = "ne"
    ng = "ng"
    nl = "nl"
    nn = "nn"
    no = "no"
    nr = "nr"
    nv = "nv"
    ny = "ny"
    oc = "oc"
    oj = "oj"
    om = "om"
    or_ = "or"
    os = "os"
    ot = "ot"  # codespell:ignore
    pa = "pa"
    pi = "pi"
    pl = "pl"
    ps = "ps"
    pt = "pt"
    qu = "qu"
    rm = "rm"
    rn = "rn"
    ro = "ro"
    ru = "ru"
    rw = "rw"
    sa = "sa"
    sar = "sar"
    sd = "sd"
    se = "se"
    sg = "sg"
    si = "si"
    sk = "sk"
    sl = "sl"
    sm = "sm"
    sn = "sn"
    so = "so"
    sq = "sq"
    sr = "sr"
    ss = "ss"
    st = "st"
    su = "su"
    sv = "sv"
    sw = "sw"
    ta = "ta"
    te = "te"  # codespell:ignore
    tg = "tg"
    th = "th"
    ti = "ti"
    tk = "tk"
    tl = "tl"
    tn = "tn"
    to = "to"
    tr = "tr"
    ts = "ts"
    tt = "tt"
    tw = "tw"
    ty = "ty"
    ug = "ug"
    uk = "uk"
    ur = "ur"
    uz = "uz"
    ve = "ve"
    vi = "vi"
    vo = "vo"
    wa = "wa"
    wo = "wo"
    xh = "xh"
    yi = "yi"
    yo = "yo"
    za = "za"
    zh = "zh"
    zu = "zu"


class AccessMode(Enum):
    access_mode_free = "access_mode-free"
    access_mode_free_conditionally = "access_mode-free_conditionally"
    access_mode_other = "access_mode-other"
    access_mode_paid = "access_mode-paid"
    access_mode_peer_reviewed = "access_mode-peer_reviewed"


class TargetUser(Enum):
    target_user_businesses = "target_user-businesses"
    target_user_funders = "target_user-funders"
    target_user_innovators = "target_user-innovators"
    target_user_other = "target_user-other"
    target_user_policy_makers = "target_user-policy_makers"
    target_user_providers = "target_user-providers"
    target_user_research_communities = "target_user-research_communities"
    target_user_research_groups = "target_user-research_groups"
    target_user_research_infrastructure_managers = (
        "target_user-research_infrastructure_managers"
    )
    target_user_research_managers = "target_user-research_managers"
    target_user_research_networks = "target_user-research_networks"
    target_user_research_organisations = "target_user-research_organisations"
    target_user_research_projects = "target_user-research_projects"
    target_user_researchers = "target_user-researchers"
    target_user_resource_managers = "target_user-resource_managers"
    target_user_resource_provider_managers = "target_user-resource_provider_managers"
    target_user_publishers = "target_user-publishers"
    target_user_students = "target_user-students"


class TRL(Enum):
    trl_1 = "trl-1"
    trl_2 = "trl-2"
    trl_3 = "trl-3"
    trl_4 = "trl-4"
    trl_5 = "trl-5"
    trl_6 = "trl-6"
    trl_7 = "trl-7"
    trl_8 = "trl-8"
    trl_9 = "trl-9"


class OrderType(Enum):
    order_type_fully_open_access = "order_type-fully_open_access"
    order_type_open_access = "order_type-open_access"
    order_type_order_required = "order_type-order_required"
    order_type_other = "order_type-other"


class AlternativeIdentifier(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str = Field(
        min_length=1, description="Type of the identifier (e.g. doi, hdl)."
    )
    value: str = Field(min_length=1, description="Identifier value.")


class BaseService(BaseModel):
    """This should be expanded with specific version fields"""

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="Service identifier (same as service bundle ID).")
    alternativeIdentifiers: list[AlternativeIdentifier] = Field(
        [], description="Alternative identifiers for the service.", min_length=0
    )
    abbreviation: str | None = Field(
        None, description="Abbreviation of the service name.", min_length=1
    )
    name: str = Field(..., description="Full name of the service.", min_length=1)
    webpage: AnyUrl = Field(..., description="URL of the service webpage.")
    description: str = Field(
        ..., description="Detailed description of the service.", min_length=1
    )
    tagline: str | None = Field(
        description="Short tagline summarising the service.", min_length=1
    )
    logo: AnyUrl | None = Field(None, description="URL of the service logo.")
    targetUsers: list[TargetUser] = Field(
        ..., description="Intended target users.", min_length=1
    )
    accessModes: list[AccessMode] | None = Field(
        None, description="Access mode provided by the service.", min_length=1
    )
    tags: list[str] | None = Field(
        description="Free-text tags for the service.", min_length=0
    )
    languageAvailabilities: list[LanguageCode] = Field(
        ...,
        description="Languages available for the service (ISO 639-1 codes).",
        min_length=1,
    )
    helpdeskEmail: EmailStr | None = Field(None, description="Helpdesk contact email.")
    securityContactEmail: EmailStr | None = Field(
        None, description="Security contact email."
    )
    trl: TRL = Field(..., description="Technology readiness level.")
    userManual: AnyUrl | None = Field(None, description="URL for the user manual.")
    termsOfUse: AnyUrl | None = Field(None, description="URL for the terms of use.")
    privacyPolicy: AnyUrl | None = Field(
        None, description="URL for the privacy policy."
    )
    accessPolicy: AnyUrl | None = Field(None, description="URL for the access policy.")
    orderType: OrderType = Field(..., description="Ordering modality for the service.")


class EOSCServiceBundleBase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ..., description="Unique identifier for the service bundle.", min_length=1
    )
