# generated by datamodel-codegen:
#   filename:  eosc_service_catalogue.schema_v3.json
#   timestamp: 2026-05-08T10:47:24+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, ConfigDict, EmailStr, Field, RootModel, constr


class NonEmptyString(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class URI(RootModel[AnyUrl]):
    root: AnyUrl


class Email(RootModel[EmailStr]):
    root: EmailStr


class LanguageCode(Enum):
    aa = "aa"
    ab = "ab"
    ae = "ae"
    af = "af"
    ak = "ak"
    am = "am"
    an = "an"
    ar = "ar"
    as_ = "as"
    av = "av"
    ay = "ay"
    az = "az"
    ba = "ba"
    be = "be"
    bg = "bg"
    bh = "bh"
    bi = "bi"
    bm = "bm"
    bn = "bn"
    bo = "bo"
    br = "br"
    bs = "bs"
    ca = "ca"
    ce = "ce"
    ch = "ch"
    co = "co"
    cr = "cr"
    cs = "cs"
    cu = "cu"
    cv = "cv"
    cy = "cy"
    da = "da"
    de = "de"
    dv = "dv"
    dz = "dz"
    ee = "ee"
    el = "el"
    en = "en"
    eo = "eo"
    es = "es"
    et = "et"
    eu = "eu"
    fa = "fa"
    ff = "ff"
    fi = "fi"
    fj = "fj"
    fo = "fo"  # codespell:ignore
    fr = "fr"
    fy = "fy"
    ga = "ga"
    gd = "gd"
    gl = "gl"
    gn = "gn"
    gu = "gu"
    gv = "gv"
    ha = "ha"
    he = "he"
    hi = "hi"
    ho = "ho"
    hr = "hr"
    ht = "ht"
    hu = "hu"
    hy = "hy"
    hz = "hz"
    ia = "ia"
    id = "id"
    ie = "ie"
    ig = "ig"
    ii = "ii"
    iii = "iii"
    ik = "ik"
    io = "io"
    is_ = "is"
    it = "it"
    iu = "iu"
    ja = "ja"
    jv = "jv"
    ka = "ka"
    kg = "kg"
    ki = "ki"
    kj = "kj"
    kk = "kk"
    kl = "kl"
    km = "km"
    kn = "kn"
    ko = "ko"
    kr = "kr"
    ks = "ks"
    ku = "ku"
    kv = "kv"
    kw = "kw"
    ky = "ky"
    la = "la"
    lb = "lb"
    li = "li"
    ln = "ln"
    lo = "lo"
    lt = "lt"
    lu = "lu"
    lv = "lv"
    mg = "mg"
    mh = "mh"
    mi = "mi"
    mk = "mk"
    ml = "ml"
    mn = "mn"
    mr = "mr"
    ms = "ms"
    mt = "mt"
    my = "my"
    na = "na"
    nb = "nb"
    nd = "nd"  # codespell:ignore
    ne = "ne"
    ng = "ng"
    nl = "nl"
    nn = "nn"
    no = "no"
    nr = "nr"
    nv = "nv"
    ny = "ny"
    oc = "oc"
    oj = "oj"
    om = "om"
    or_ = "or"
    os = "os"
    ot = "ot"  # codespell:ignore
    pa = "pa"
    pi = "pi"
    pl = "pl"
    ps = "ps"
    pt = "pt"
    qu = "qu"
    rm = "rm"
    rn = "rn"
    ro = "ro"
    ru = "ru"
    rw = "rw"
    sa = "sa"
    sar = "sar"
    sd = "sd"
    se = "se"
    sg = "sg"
    si = "si"
    sk = "sk"
    sl = "sl"
    sm = "sm"
    sn = "sn"
    so = "so"
    sq = "sq"
    sr = "sr"
    ss = "ss"
    st = "st"
    su = "su"
    sv = "sv"
    sw = "sw"
    ta = "ta"
    te = "te"  # codespell:ignore wrod
    tg = "tg"
    th = "th"
    ti = "ti"
    tk = "tk"
    tl = "tl"
    tn = "tn"
    to = "to"
    tr = "tr"
    ts = "ts"
    tt = "tt"
    tw = "tw"
    ty = "ty"
    ug = "ug"
    uk = "uk"
    ur = "ur"
    uz = "uz"
    ve = "ve"
    vi = "vi"
    vo = "vo"
    wa = "wa"
    wo = "wo"
    xh = "xh"
    yi = "yi"
    yo = "yo"
    za = "za"
    zh = "zh"
    zu = "zu"


class AccessMode(Enum):
    access_mode_free = "access_mode-free"
    access_mode_free_conditionally = "access_mode-free_conditionally"
    access_mode_other = "access_mode-other"
    access_mode_paid = "access_mode-paid"
    access_mode_peer_reviewed = "access_mode-peer_reviewed"


class TargetUser(Enum):
    target_user_businesses = "target_user-businesses"
    target_user_funders = "target_user-funders"
    target_user_innovators = "target_user-innovators"
    target_user_other = "target_user-other"
    target_user_policy_makers = "target_user-policy_makers"
    target_user_providers = "target_user-providers"
    target_user_research_communities = "target_user-research_communities"
    target_user_research_groups = "target_user-research_groups"
    target_user_research_infrastructure_managers = (
        "target_user-research_infrastructure_managers"
    )
    target_user_research_managers = "target_user-research_managers"
    target_user_research_networks = "target_user-research_networks"
    target_user_research_organisations = "target_user-research_organisations"
    target_user_research_projects = "target_user-research_projects"
    target_user_researchers = "target_user-researchers"
    target_user_resource_managers = "target_user-resource_managers"
    target_user_resource_provider_managers = "target_user-resource_provider_managers"
    target_user_publishers = "target_user-publishers"
    target_user_students = "target_user-students"


class TRL(Enum):
    trl_1 = "trl-1"
    trl_2 = "trl-2"
    trl_3 = "trl-3"
    trl_4 = "trl-4"
    trl_5 = "trl-5"
    trl_6 = "trl-6"
    trl_7 = "trl-7"
    trl_8 = "trl-8"
    trl_9 = "trl-9"


class OrderType(Enum):
    order_type_fully_open_access = "order_type-fully_open_access"
    order_type_open_access = "order_type-open_access"
    order_type_order_required = "order_type-order_required"
    order_type_other = "order_type-other"


class CategoryId(Enum):
    category_access_physical_and_eInfrastructures_compute = (
        "category-access_physical_and_eInfrastructures-compute"
    )
    category_access_physical_and_eInfrastructures_data_storage = (
        "category-access_physical_and_eInfrastructures-data_storage"
    )
    category_access_physical_and_eInfrastructures_instrument_and_equipment = (
        "category-access_physical_and_eInfrastructures-instrument_and_equipment"
    )
    category_access_physical_and_eInfrastructures_material_storage = (
        "category-access_physical_and_eInfrastructures-material_storage"
    )
    category_access_physical_and_eInfrastructures_network = (
        "category-access_physical_and_eInfrastructures-network"
    )
    category_aggregators_and_integrators_aggregators_and_integrators = (
        "category-aggregators_and_integrators-aggregators_and_integrators"
    )
    category_other_other = "category-other-other"
    category_processing_and_analysis_data_analysis = (
        "category-processing_and_analysis-data_analysis"
    )
    category_processing_and_analysis_data_management = (
        "category-processing_and_analysis-data_management"
    )
    category_processing_and_analysis_measurement_and_materials_analysis = (
        "category-processing_and_analysis-measurement_and_materials_analysis"
    )
    category_security_and_operations_operations_and_infrastructure_management_services = "category-security_and_operations-operations_and_infrastructure_management_services"
    category_security_and_operations_security_and_identity = (
        "category-security_and_operations-security_and_identity"
    )
    category_sharing_and_discovery_applications = (
        "category-sharing_and_discovery-applications"
    )
    category_sharing_and_discovery_data = "category-sharing_and_discovery-data"
    category_sharing_and_discovery_development_resources = (
        "category-sharing_and_discovery-development_resources"
    )
    category_sharing_and_discovery_samples = "category-sharing_and_discovery-samples"
    category_sharing_and_discovery_scholarly_communication = (
        "category-sharing_and_discovery-scholarly_communication"
    )
    category_sharing_and_discovery_software = "category-sharing_and_discovery-software"
    category_training_and_support_consultancy_and_support = (
        "category-training_and_support-consultancy_and_support"
    )
    category_training_and_support_education_and_training = (
        "category-training_and_support-education_and_training"
    )


class SubcategoryId1(Enum):
    subcategory_access_physical_and_eInfrastructures_compute_container_management = (
        "subcategory-access_physical_and_eInfrastructures-compute-container_management"
    )
    subcategory_access_physical_and_eInfrastructures_compute_hpc_access = (
        "subcategory-access_physical_and_eInfrastructures-compute-hpc_access"
    )
    subcategory_access_physical_and_eInfrastructures_compute_interactive_notebooks = (
        "subcategory-access_physical_and_eInfrastructures-compute-interactive_notebooks"
    )
    subcategory_access_physical_and_eInfrastructures_compute_job_execution = (
        "subcategory-access_physical_and_eInfrastructures-compute-job_execution"
    )
    subcategory_access_physical_and_eInfrastructures_compute_orchestration = (
        "subcategory-access_physical_and_eInfrastructures-compute-orchestration"
    )
    subcategory_access_physical_and_eInfrastructures_compute_other = (
        "subcategory-access_physical_and_eInfrastructures-compute-other"
    )
    subcategory_access_physical_and_eInfrastructures_compute_serverless_applications_repository = "subcategory-access_physical_and_eInfrastructures-compute-serverless_applications_repository"
    subcategory_access_physical_and_eInfrastructures_compute_virtual_machine_management = "subcategory-access_physical_and_eInfrastructures-compute-virtual_machine_management"
    subcategory_access_physical_and_eInfrastructures_compute_workload_management = (
        "subcategory-access_physical_and_eInfrastructures-compute-workload_management"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_archive = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-archive"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_backup = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-backup"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_data = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-data"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_digital_preservation = "subcategory-access_physical_and_eInfrastructures-data_storage-digital_preservation"
    subcategory_access_physical_and_eInfrastructures_data_storage_disk = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-disk"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_file = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-file"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_online = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-online"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_other = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-other"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_queue = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-queue"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_recovery = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-recovery"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_replicated = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-replicated"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_synchronised = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-synchronised"
    )
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_chromatographer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-chromatographer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_cytometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-cytometer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_digitisation_equipment = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-digitisation_equipment"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_geophysical = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-geophysical"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_laser = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-laser"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_microscopy = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-microscopy"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_monument_maintenance_equipment = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-monument_maintenance_equipment"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_other = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-other"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_radiation = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-radiation"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_spectrometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-spectrometer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_spectrophotometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-spectrophotometer"
    subcategory_access_physical_and_eInfrastructures_material_storage_archiving = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-archiving"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_assembly = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-assembly"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_disposal = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-disposal"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_fulfilment = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-fulfilment"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_other = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-other"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_packaging = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-packaging"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_preservation = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-preservation"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_quality_inspecting = "subcategory-access_physical_and_eInfrastructures-material_storage-quality_inspecting"
    subcategory_access_physical_and_eInfrastructures_material_storage_repository = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-repository"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_reworking = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-reworking"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_sorting = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-sorting"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_warehousing = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-warehousing"
    )
    subcategory_access_physical_and_eInfrastructures_network_content_delivery_network = "subcategory-access_physical_and_eInfrastructures-network-content_delivery_network"
    subcategory_access_physical_and_eInfrastructures_network_direct_connect = (
        "subcategory-access_physical_and_eInfrastructures-network-direct_connect"
    )
    subcategory_access_physical_and_eInfrastructures_network_dns = (
        "subcategory-access_physical_and_eInfrastructures-network-dns"
    )
    subcategory_access_physical_and_eInfrastructures_network_exchange = (
        "subcategory-access_physical_and_eInfrastructures-network-exchange"
    )
    subcategory_access_physical_and_eInfrastructures_network_load_balancer = (
        "subcategory-access_physical_and_eInfrastructures-network-load_balancer"
    )
    subcategory_access_physical_and_eInfrastructures_network_other = (
        "subcategory-access_physical_and_eInfrastructures-network-other"
    )
    subcategory_access_physical_and_eInfrastructures_network_traffic_manager = (
        "subcategory-access_physical_and_eInfrastructures-network-traffic_manager"
    )
    subcategory_access_physical_and_eInfrastructures_network_virtual_nework = (
        "subcategory-access_physical_and_eInfrastructures-network-virtual_nework"
    )
    subcategory_access_physical_and_eInfrastructures_network_vpn_gateway = (
        "subcategory-access_physical_and_eInfrastructures-network-vpn_gateway"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_applications = "subcategory-aggregators_and_integrators-aggregators_and_integrators-applications"
    subcategory_aggregators_and_integrators_aggregators_and_integrators_data = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-data"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_other = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-other"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_services = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-services"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_software = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-software"
    )
    subcategory_other_other_other = "subcategory-other-other-other"
    subcategory_processing_and_analysis_data_analysis_2d_3d_digitisation = (
        "subcategory-processing_and_analysis-data_analysis-2d_3d_digitisation"
    )
    subcategory_processing_and_analysis_data_analysis_artificial_intelligence = (
        "subcategory-processing_and_analysis-data_analysis-artificial_intelligence"
    )
    subcategory_processing_and_analysis_data_analysis_data_extrapolation = (
        "subcategory-processing_and_analysis-data_analysis-data_extrapolation"
    )
    subcategory_processing_and_analysis_data_analysis_forecast = (
        "subcategory-processing_and_analysis-data_analysis-forecast"
    )
    subcategory_processing_and_analysis_data_analysis_image_data_analysis = (
        "subcategory-processing_and_analysis-data_analysis-image_data_analysis"
    )
    subcategory_processing_and_analysis_data_analysis_machine_learning = (
        "subcategory-processing_and_analysis-data_analysis-machine_learning"
    )
    subcategory_processing_and_analysis_data_analysis_other = (
        "subcategory-processing_and_analysis-data_analysis-other"
    )
    subcategory_processing_and_analysis_data_analysis_quality_assesment = (
        "subcategory-processing_and_analysis-data_analysis-quality_assesment"
    )
    subcategory_processing_and_analysis_data_analysis_visualization = (
        "subcategory-processing_and_analysis-data_analysis-visualization"
    )
    subcategory_processing_and_analysis_data_analysis_workflows = (
        "subcategory-processing_and_analysis-data_analysis-workflows"
    )
    subcategory_processing_and_analysis_data_management_access = (
        "subcategory-processing_and_analysis-data_management-access"
    )
    subcategory_processing_and_analysis_data_management_annotation = (
        "subcategory-processing_and_analysis-data_management-annotation"
    )
    subcategory_processing_and_analysis_data_management_anonymisation = (
        "subcategory-processing_and_analysis-data_management-anonymisation"
    )
    subcategory_processing_and_analysis_data_management_brokering = (
        "subcategory-processing_and_analysis-data_management-brokering"
    )
    subcategory_processing_and_analysis_data_management_digitisation = (
        "subcategory-processing_and_analysis-data_management-digitisation"
    )
    subcategory_processing_and_analysis_data_management_discovery = (
        "subcategory-processing_and_analysis-data_management-discovery"
    )
    subcategory_processing_and_analysis_data_management_embargo = (
        "subcategory-processing_and_analysis-data_management-embargo"
    )
    subcategory_processing_and_analysis_data_management_interlinking = (
        "subcategory-processing_and_analysis-data_management-interlinking"
    )
    subcategory_processing_and_analysis_data_management_maintenance = (
        "subcategory-processing_and_analysis-data_management-maintenance"
    )
    subcategory_processing_and_analysis_data_management_mining = (
        "subcategory-processing_and_analysis-data_management-mining"
    )
    subcategory_processing_and_analysis_data_management_other = (
        "subcategory-processing_and_analysis-data_management-other"
    )
    subcategory_processing_and_analysis_data_management_persistent_identifier = (
        "subcategory-processing_and_analysis-data_management-persistent_identifier"
    )
    subcategory_processing_and_analysis_data_management_preservation = (
        "subcategory-processing_and_analysis-data_management-preservation"
    )
    subcategory_processing_and_analysis_data_management_publishing = (
        "subcategory-processing_and_analysis-data_management-publishing"
    )
    subcategory_processing_and_analysis_data_management_registration = (
        "subcategory-processing_and_analysis-data_management-registration"
    )
    subcategory_processing_and_analysis_data_management_transfer = (
        "subcategory-processing_and_analysis-data_management-transfer"
    )
    subcategory_processing_and_analysis_data_management_validation = (
        "subcategory-processing_and_analysis-data_management-validation"
    )
    subcategory_processing_and_analysis_measurement_and_materials_analysis_analysis = "subcategory-processing_and_analysis-measurement_and_materials_analysis-analysis"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_characterisation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-characterisation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_maintenance_and_modification = "subcategory-processing_and_analysis-measurement_and_materials_analysis-maintenance_and_modification"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_other = (
        "subcategory-processing_and_analysis-measurement_and_materials_analysis-other"
    )
    subcategory_processing_and_analysis_measurement_and_materials_analysis_production = "subcategory-processing_and_analysis-measurement_and_materials_analysis-production"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_testing_and_validation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-testing_and_validation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_validation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-validation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_workflows = "subcategory-processing_and_analysis-measurement_and_materials_analysis-workflows"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_accounting = "subcategory-security_and_operations-operations_and_infrastructure_management_services-accounting"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_analysis = "subcategory-security_and_operations-operations_and_infrastructure_management_services-analysis"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_billing = "subcategory-security_and_operations-operations_and_infrastructure_management_services-billing"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_configuration = "subcategory-security_and_operations-operations_and_infrastructure_management_services-configuration"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_coordination = "subcategory-security_and_operations-operations_and_infrastructure_management_services-coordination"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_helpdesk = "subcategory-security_and_operations-operations_and_infrastructure_management_services-helpdesk"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_monitoring = "subcategory-security_and_operations-operations_and_infrastructure_management_services-monitoring"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_order_management = "subcategory-security_and_operations-operations_and_infrastructure_management_services-order_management"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_other = "subcategory-security_and_operations-operations_and_infrastructure_management_services-other"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_transportation = "subcategory-security_and_operations-operations_and_infrastructure_management_services-transportation"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_utilities = "subcategory-security_and_operations-operations_and_infrastructure_management_services-utilities"
    subcategory_security_and_operations_security_and_identity_certification_authority = "subcategory-security_and_operations-security_and_identity-certification_authority"
    subcategory_security_and_operations_security_and_identity_coordination = (
        "subcategory-security_and_operations-security_and_identity-coordination"
    )
    subcategory_security_and_operations_security_and_identity_firewall = (
        "subcategory-security_and_operations-security_and_identity-firewall"
    )
    subcategory_security_and_operations_security_and_identity_group_management = (
        "subcategory-security_and_operations-security_and_identity-group_management"
    )
    subcategory_security_and_operations_security_and_identity_identity_and_access_management = "subcategory-security_and_operations-security_and_identity-identity_and_access_management"
    subcategory_security_and_operations_security_and_identity_other = (
        "subcategory-security_and_operations-security_and_identity-other"
    )
    subcategory_security_and_operations_security_and_identity_single_sign_on = (
        "subcategory-security_and_operations-security_and_identity-single_sign_on"
    )
    subcategory_security_and_operations_security_and_identity_threat_protection = (
        "subcategory-security_and_operations-security_and_identity-threat_protection"
    )
    subcategory_security_and_operations_security_and_identity_tools = (
        "subcategory-security_and_operations-security_and_identity-tools"
    )
    subcategory_security_and_operations_security_and_identity_user_authentication = (
        "subcategory-security_and_operations-security_and_identity-user_authentication"
    )
    subcategory_sharing_and_discovery_applications_applications_repository = (
        "subcategory-sharing_and_discovery-applications-applications_repository"
    )
    subcategory_sharing_and_discovery_applications_business = (
        "subcategory-sharing_and_discovery-applications-business"
    )
    subcategory_sharing_and_discovery_applications_collaboration = (
        "subcategory-sharing_and_discovery-applications-collaboration"
    )
    subcategory_sharing_and_discovery_applications_communication = (
        "subcategory-sharing_and_discovery-applications-communication"
    )
    subcategory_sharing_and_discovery_applications_education = (
        "subcategory-sharing_and_discovery-applications-education"
    )
    subcategory_sharing_and_discovery_applications_other = (
        "subcategory-sharing_and_discovery-applications-other"
    )
    subcategory_sharing_and_discovery_applications_productivity = (
        "subcategory-sharing_and_discovery-applications-productivity"
    )
    subcategory_sharing_and_discovery_applications_social_networking = (
        "subcategory-sharing_and_discovery-applications-social_networking"
    )
    subcategory_sharing_and_discovery_applications_utilities = (
        "subcategory-sharing_and_discovery-applications-utilities"
    )
    subcategory_sharing_and_discovery_data_clinical_trial_data = (
        "subcategory-sharing_and_discovery-data-clinical_trial_data"
    )
    subcategory_sharing_and_discovery_data_data_archives = (
        "subcategory-sharing_and_discovery-data-data_archives"
    )
    subcategory_sharing_and_discovery_data_epidemiological_data = (
        "subcategory-sharing_and_discovery-data-epidemiological_data"
    )
    subcategory_sharing_and_discovery_data_government_and_agency_data = (
        "subcategory-sharing_and_discovery-data-government_and_agency_data"
    )
    subcategory_sharing_and_discovery_data_metadata = (
        "subcategory-sharing_and_discovery-data-metadata"
    )
    subcategory_sharing_and_discovery_data_online_service_data = (
        "subcategory-sharing_and_discovery-data-online_service_data"
    )
    subcategory_sharing_and_discovery_data_other = (
        "subcategory-sharing_and_discovery-data-other"
    )
    subcategory_sharing_and_discovery_data_scientific_research_data = (
        "subcategory-sharing_and_discovery-data-scientific_research_data"
    )
    subcategory_sharing_and_discovery_data_statistical_data = (
        "subcategory-sharing_and_discovery-data-statistical_data"
    )
    subcategory_sharing_and_discovery_development_resources_apis_repository_gateway = "subcategory-sharing_and_discovery-development_resources-apis_repository_gateway"
    subcategory_sharing_and_discovery_development_resources_developer_tools = (
        "subcategory-sharing_and_discovery-development_resources-developer_tools"
    )
    subcategory_sharing_and_discovery_development_resources_other = (
        "subcategory-sharing_and_discovery-development_resources-other"
    )
    subcategory_sharing_and_discovery_development_resources_simulation_tools = (
        "subcategory-sharing_and_discovery-development_resources-simulation_tools"
    )
    subcategory_sharing_and_discovery_development_resources_software_development_kits = "subcategory-sharing_and_discovery-development_resources-software_development_kits"
    subcategory_sharing_and_discovery_development_resources_software_libraries = (
        "subcategory-sharing_and_discovery-development_resources-software_libraries"
    )
    subcategory_sharing_and_discovery_samples_biological_samples = (
        "subcategory-sharing_and_discovery-samples-biological_samples"
    )
    subcategory_sharing_and_discovery_samples_characterisation = (
        "subcategory-sharing_and_discovery-samples-characterisation"
    )
    subcategory_sharing_and_discovery_samples_chemical_compounds_library = (
        "subcategory-sharing_and_discovery-samples-chemical_compounds_library"
    )
    subcategory_sharing_and_discovery_samples_other = (
        "subcategory-sharing_and_discovery-samples-other"
    )
    subcategory_sharing_and_discovery_samples_preparation = (
        "subcategory-sharing_and_discovery-samples-preparation"
    )
    subcategory_sharing_and_discovery_scholarly_communication_analysis = (
        "subcategory-sharing_and_discovery-scholarly_communication-analysis"
    )
    subcategory_sharing_and_discovery_scholarly_communication_assessment = (
        "subcategory-sharing_and_discovery-scholarly_communication-assessment"
    )
    subcategory_sharing_and_discovery_scholarly_communication_discovery = (
        "subcategory-sharing_and_discovery-scholarly_communication-discovery"
    )
    subcategory_sharing_and_discovery_scholarly_communication_other = (
        "subcategory-sharing_and_discovery-scholarly_communication-other"
    )
    subcategory_sharing_and_discovery_scholarly_communication_outreach = (
        "subcategory-sharing_and_discovery-scholarly_communication-outreach"
    )
    subcategory_sharing_and_discovery_scholarly_communication_preparation = (
        "subcategory-sharing_and_discovery-scholarly_communication-preparation"
    )
    subcategory_sharing_and_discovery_scholarly_communication_publication = (
        "subcategory-sharing_and_discovery-scholarly_communication-publication"
    )
    subcategory_sharing_and_discovery_scholarly_communication_writing = (
        "subcategory-sharing_and_discovery-scholarly_communication-writing"
    )
    subcategory_sharing_and_discovery_software_libraries = (
        "subcategory-sharing_and_discovery-software-libraries"
    )
    subcategory_sharing_and_discovery_software_other = (
        "subcategory-sharing_and_discovery-software-other"
    )
    subcategory_sharing_and_discovery_software_platform = (
        "subcategory-sharing_and_discovery-software-platform"
    )
    subcategory_sharing_and_discovery_software_software_package = (
        "subcategory-sharing_and_discovery-software-software_package"
    )
    subcategory_sharing_and_discovery_software_software_repository = (
        "subcategory-sharing_and_discovery-software-software_repository"
    )
    subcategory_training_and_support_consultancy_and_support_application_optimisation = "subcategory-training_and_support-consultancy_and_support-application_optimisation"
    subcategory_training_and_support_consultancy_and_support_application_porting = (
        "subcategory-training_and_support-consultancy_and_support-application_porting"
    )
    subcategory_training_and_support_consultancy_and_support_application_scaling = (
        "subcategory-training_and_support-consultancy_and_support-application_scaling"
    )
    subcategory_training_and_support_consultancy_and_support_audit_and_assessment = (
        "subcategory-training_and_support-consultancy_and_support-audit_and_assessment"
    )
    subcategory_training_and_support_consultancy_and_support_benchmarking = (
        "subcategory-training_and_support-consultancy_and_support-benchmarking"
    )
    subcategory_training_and_support_consultancy_and_support_calibration = (
        "subcategory-training_and_support-consultancy_and_support-calibration"
    )
    subcategory_training_and_support_consultancy_and_support_certification = (
        "subcategory-training_and_support-consultancy_and_support-certification"
    )
    subcategory_training_and_support_consultancy_and_support_consulting = (
        "subcategory-training_and_support-consultancy_and_support-consulting"
    )
    subcategory_training_and_support_consultancy_and_support_methodology_development = "subcategory-training_and_support-consultancy_and_support-methodology_development"
    subcategory_training_and_support_consultancy_and_support_modeling_and_simulation = "subcategory-training_and_support-consultancy_and_support-modeling_and_simulation"
    subcategory_training_and_support_consultancy_and_support_other = (
        "subcategory-training_and_support-consultancy_and_support-other"
    )
    subcategory_training_and_support_consultancy_and_support_prototype_development = (
        "subcategory-training_and_support-consultancy_and_support-prototype_development"
    )
    subcategory_training_and_support_consultancy_and_support_software_development = (
        "subcategory-training_and_support-consultancy_and_support-software_development"
    )
    subcategory_training_and_support_consultancy_and_support_software_improvement = (
        "subcategory-training_and_support-consultancy_and_support-software_improvement"
    )
    subcategory_training_and_support_consultancy_and_support_technology_transfer = (
        "subcategory-training_and_support-consultancy_and_support-technology_transfer"
    )
    subcategory_training_and_support_consultancy_and_support_testing = (
        "subcategory-training_and_support-consultancy_and_support-testing"
    )
    subcategory_training_and_support_education_and_training_in_house_courses = (
        "subcategory-training_and_support-education_and_training-in_house_courses"
    )
    subcategory_training_and_support_education_and_training_online_courses = (
        "subcategory-training_and_support-education_and_training-online_courses"
    )
    subcategory_training_and_support_education_and_training_open_registration_courses = "subcategory-training_and_support-education_and_training-open_registration_courses"
    subcategory_training_and_support_education_and_training_other = (
        "subcategory-training_and_support-education_and_training-other"
    )
    subcategory_training_and_support_education_and_training_related_training = (
        "subcategory-training_and_support-education_and_training-related_training"
    )
    subcategory_training_and_support_education_and_training_required_training = (
        "subcategory-training_and_support-education_and_training-required_training"
    )
    subcategory_training_and_support_education_and_training_training_platform = (
        "subcategory-training_and_support-education_and_training-training_platform"
    )
    subcategory_training_and_support_education_and_training_training_tool = (
        "subcategory-training_and_support-education_and_training-training_tool"
    )


class SubcategoryId(RootModel[SubcategoryId1 | None]):
    root: SubcategoryId1 | None


class ScientificDomainId(Enum):
    scientific_domain_agricultural_sciences = "scientific_domain-agricultural_sciences"
    scientific_domain_engineering_and_technology = (
        "scientific_domain-engineering_and_technology"
    )
    scientific_domain_generic = "scientific_domain-generic"
    scientific_domain_humanities = "scientific_domain-humanities"
    scientific_domain_medical_and_health_sciences = (
        "scientific_domain-medical_and_health_sciences"
    )
    scientific_domain_natural_sciences = "scientific_domain-natural_sciences"
    scientific_domain_other = "scientific_domain-other"
    scientific_domain_social_sciences = "scientific_domain-social_sciences"


class ScientificSubdomainId1(Enum):
    scientific_subdomain_agricultural_sciences_agricultural_biotechnology = (
        "scientific_subdomain-agricultural_sciences-agricultural_biotechnology"
    )
    scientific_subdomain_agricultural_sciences_agriculture_forestry_and_fisheries = (
        "scientific_subdomain-agricultural_sciences-agriculture_forestry_and_fisheries"
    )
    scientific_subdomain_agricultural_sciences_animal_and_dairy_sciences = (
        "scientific_subdomain-agricultural_sciences-animal_and_dairy_sciences"
    )
    scientific_subdomain_agricultural_sciences_other_agricultural_sciences = (
        "scientific_subdomain-agricultural_sciences-other_agricultural_sciences"
    )
    scientific_subdomain_agricultural_sciences_veterinary_sciences = (
        "scientific_subdomain-agricultural_sciences-veterinary_sciences"
    )
    scientific_subdomain_engineering_and_technology_chemical_engineering = (
        "scientific_subdomain-engineering_and_technology-chemical_engineering"
    )
    scientific_subdomain_engineering_and_technology_civil_engineering = (
        "scientific_subdomain-engineering_and_technology-civil_engineering"
    )
    scientific_subdomain_engineering_and_technology_electrical_electronic_and_information_engineering = "scientific_subdomain-engineering_and_technology-electrical_electronic_and_information_engineering"
    scientific_subdomain_engineering_and_technology_environmental_biotechnology = (
        "scientific_subdomain-engineering_and_technology-environmental_biotechnology"
    )
    scientific_subdomain_engineering_and_technology_environmental_engineering = (
        "scientific_subdomain-engineering_and_technology-environmental_engineering"
    )
    scientific_subdomain_engineering_and_technology_industrial_biotechnology = (
        "scientific_subdomain-engineering_and_technology-industrial_biotechnology"
    )
    scientific_subdomain_engineering_and_technology_materials_engineering = (
        "scientific_subdomain-engineering_and_technology-materials_engineering"
    )
    scientific_subdomain_engineering_and_technology_mechanical_engineering = (
        "scientific_subdomain-engineering_and_technology-mechanical_engineering"
    )
    scientific_subdomain_engineering_and_technology_medical_engineering = (
        "scientific_subdomain-engineering_and_technology-medical_engineering"
    )
    scientific_subdomain_engineering_and_technology_nanotechnology = (
        "scientific_subdomain-engineering_and_technology-nanotechnology"
    )
    scientific_subdomain_engineering_and_technology_other_engineering_and_technology_sciences = "scientific_subdomain-engineering_and_technology-other_engineering_and_technology_sciences"
    scientific_subdomain_generic_generic = "scientific_subdomain-generic-generic"
    scientific_subdomain_humanities_arts = "scientific_subdomain-humanities-arts"
    scientific_subdomain_humanities_history_and_archaeology = (
        "scientific_subdomain-humanities-history_and_archaeology"
    )
    scientific_subdomain_humanities_languages_and_literature = (
        "scientific_subdomain-humanities-languages_and_literature"
    )
    scientific_subdomain_humanities_other_humanities = (
        "scientific_subdomain-humanities-other_humanities"
    )
    scientific_subdomain_humanities_philosophy_ethics_and_religion = (
        "scientific_subdomain-humanities-philosophy_ethics_and_religion"
    )
    scientific_subdomain_medical_and_health_sciences_basic_medicine = (
        "scientific_subdomain-medical_and_health_sciences-basic_medicine"
    )
    scientific_subdomain_medical_and_health_sciences_clinical_medicine = (
        "scientific_subdomain-medical_and_health_sciences-clinical_medicine"
    )
    scientific_subdomain_medical_and_health_sciences_health_sciences = (
        "scientific_subdomain-medical_and_health_sciences-health_sciences"
    )
    scientific_subdomain_medical_and_health_sciences_medical_biotechnology = (
        "scientific_subdomain-medical_and_health_sciences-medical_biotechnology"
    )
    scientific_subdomain_medical_and_health_sciences_other_medical_sciences = (
        "scientific_subdomain-medical_and_health_sciences-other_medical_sciences"
    )
    scientific_subdomain_natural_sciences_biological_sciences = (
        "scientific_subdomain-natural_sciences-biological_sciences"
    )
    scientific_subdomain_natural_sciences_chemical_sciences = (
        "scientific_subdomain-natural_sciences-chemical_sciences"
    )
    scientific_subdomain_natural_sciences_computer_and_information_sciences = (
        "scientific_subdomain-natural_sciences-computer_and_information_sciences"
    )
    scientific_subdomain_natural_sciences_earth_and_related_environmental_sciences = (
        "scientific_subdomain-natural_sciences-earth_and_related_environmental_sciences"
    )
    scientific_subdomain_natural_sciences_mathematics = (
        "scientific_subdomain-natural_sciences-mathematics"
    )
    scientific_subdomain_natural_sciences_other_natural_sciences = (
        "scientific_subdomain-natural_sciences-other_natural_sciences"
    )
    scientific_subdomain_natural_sciences_physical_sciences = (
        "scientific_subdomain-natural_sciences-physical_sciences"
    )
    scientific_subdomain_other_other = "scientific_subdomain-other-other"
    scientific_subdomain_social_sciences_economics_and_business = (
        "scientific_subdomain-social_sciences-economics_and_business"
    )
    scientific_subdomain_social_sciences_educational_sciences = (
        "scientific_subdomain-social_sciences-educational_sciences"
    )
    scientific_subdomain_social_sciences_law = (
        "scientific_subdomain-social_sciences-law"
    )
    scientific_subdomain_social_sciences_media_and_communications = (
        "scientific_subdomain-social_sciences-media_and_communications"
    )
    scientific_subdomain_social_sciences_other_social_sciences = (
        "scientific_subdomain-social_sciences-other_social_sciences"
    )
    scientific_subdomain_social_sciences_political_sciences = (
        "scientific_subdomain-social_sciences-political_sciences"
    )
    scientific_subdomain_social_sciences_psychology = (
        "scientific_subdomain-social_sciences-psychology"
    )
    scientific_subdomain_social_sciences_social_and_economic_geography = (
        "scientific_subdomain-social_sciences-social_and_economic_geography"
    )
    scientific_subdomain_social_sciences_sociology = (
        "scientific_subdomain-social_sciences-sociology"
    )


class ScientificSubdomainId(RootModel[ScientificSubdomainId1 | None]):
    root: ScientificSubdomainId1 | None


class Tag(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class AlternativeIdentifier(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: NonEmptyString | None = Field(
        None, description="Type of the identifier (e.g. doi, hdl)."
    )
    value: NonEmptyString = Field(..., description="Identifier value.")


class ScientificDomainEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scientificDomain: ScientificDomainId
    scientificSubdomain: ScientificSubdomainId | None = None


class ServiceCategoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: CategoryId
    subcategory: SubcategoryId | None = None


class Service(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: NonEmptyString = Field(
        ..., description="Service identifier (same as service bundle ID)."
    )
    alternativeIdentifiers: list[AlternativeIdentifier] | None = Field(
        None, description="Alternative identifiers for the service.", min_length=1
    )
    abbreviation: NonEmptyString | None = Field(
        None, description="Abbreviation of the service name."
    )
    name: NonEmptyString = Field(..., description="Full name of the service.")
    webpage: URI = Field(..., description="URL of the service webpage.")
    description: NonEmptyString = Field(
        ..., description="Detailed description of the service."
    )
    tagline: NonEmptyString | None = Field(
        None, description="Short tagline summarising the service."
    )
    logo: URI | None = Field(None, description="URL of the service logo.")
    scientificDomains: list[ScientificDomainEntry] = Field(
        ..., description="Scientific domains applicable to the service.", min_length=1
    )
    categories: list[ServiceCategoryEntry] = Field(
        ..., description="Service categories.", min_length=1
    )
    targetUsers: list[TargetUser] = Field(
        ..., description="Intended target users.", min_length=1
    )
    accessModes: list[AccessMode] | None = Field(
        None, description="Access mode provided by the service.", min_length=1
    )
    tags: list[Tag] | None = Field(
        None, description="Free-text tags for the service.", min_length=1
    )
    languageAvailabilities: list[LanguageCode] = Field(
        ...,
        description="Languages available for the service (ISO 639-1 codes).",
        min_length=1,
    )
    helpdeskEmail: Email | None = Field(None, description="Helpdesk contact email.")
    securityContactEmail: Email | None = Field(
        None, description="Security contact email."
    )
    trl: TRL = Field(..., description="Technology readiness level.")
    userManual: URI | None = Field(None, description="URL for the user manual.")
    termsOfUse: URI | None = Field(None, description="URL for the terms of use.")
    privacyPolicy: URI | None = Field(None, description="URL for the privacy policy.")
    accessPolicy: URI | None = Field(None, description="URL for the access policy.")
    orderType: OrderType = Field(..., description="Ordering modality for the service.")


class EoscServiceBundleSchemaV3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: NonEmptyString = Field(
        ..., description="Unique identifier for the service bundle."
    )
    service: Service = Field(..., description="Metadata of the catalogued service.")
