# generated by datamodel-codegen:
#   filename:  eosc_service_catalogue.schema_v3.json
#   timestamp: 2026-05-08T10:47:24+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import (
    AnyUrl,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    field_validator,
)


class LanguageCode(Enum):
    aa = "aa"
    ab = "ab"
    ae = "ae"
    af = "af"
    ak = "ak"
    am = "am"
    an = "an"
    ar = "ar"
    as_ = "as"
    av = "av"
    ay = "ay"
    az = "az"
    ba = "ba"
    be = "be"
    bg = "bg"
    bh = "bh"
    bi = "bi"
    bm = "bm"
    bn = "bn"
    bo = "bo"
    br = "br"
    bs = "bs"
    ca = "ca"
    ce = "ce"
    ch = "ch"
    co = "co"
    cr = "cr"
    cs = "cs"
    cu = "cu"
    cv = "cv"
    cy = "cy"
    da = "da"
    de = "de"
    dv = "dv"
    dz = "dz"
    ee = "ee"
    el = "el"
    en = "en"
    eo = "eo"
    es = "es"
    et = "et"
    eu = "eu"
    fa = "fa"
    ff = "ff"
    fi = "fi"
    fj = "fj"
    fo = "fo"  # codespell:ignore
    fr = "fr"
    fy = "fy"
    ga = "ga"
    gd = "gd"
    gl = "gl"
    gn = "gn"
    gu = "gu"
    gv = "gv"
    ha = "ha"
    he = "he"
    hi = "hi"
    ho = "ho"
    hr = "hr"
    ht = "ht"
    hu = "hu"
    hy = "hy"
    hz = "hz"
    ia = "ia"
    id = "id"
    ie = "ie"
    ig = "ig"
    ii = "ii"
    iii = "iii"
    ik = "ik"
    io = "io"
    is_ = "is"
    it = "it"
    iu = "iu"
    ja = "ja"
    jv = "jv"
    ka = "ka"
    kg = "kg"
    ki = "ki"
    kj = "kj"
    kk = "kk"
    kl = "kl"
    km = "km"
    kn = "kn"
    ko = "ko"
    kr = "kr"
    ks = "ks"
    ku = "ku"
    kv = "kv"
    kw = "kw"
    ky = "ky"
    la = "la"
    lb = "lb"
    li = "li"
    ln = "ln"
    lo = "lo"
    lt = "lt"
    lu = "lu"
    lv = "lv"
    mg = "mg"
    mh = "mh"
    mi = "mi"
    mk = "mk"
    ml = "ml"
    mn = "mn"
    mr = "mr"
    ms = "ms"
    mt = "mt"
    my = "my"
    na = "na"
    nb = "nb"
    nd = "nd"  # codespell:ignore
    ne = "ne"
    ng = "ng"
    nl = "nl"
    nn = "nn"
    no = "no"
    nr = "nr"
    nv = "nv"
    ny = "ny"
    oc = "oc"
    oj = "oj"
    om = "om"
    or_ = "or"
    os = "os"
    ot = "ot"  # codespell:ignore
    pa = "pa"
    pi = "pi"
    pl = "pl"
    ps = "ps"
    pt = "pt"
    qu = "qu"
    rm = "rm"
    rn = "rn"
    ro = "ro"
    ru = "ru"
    rw = "rw"
    sa = "sa"
    sar = "sar"
    sd = "sd"
    se = "se"
    sg = "sg"
    si = "si"
    sk = "sk"
    sl = "sl"
    sm = "sm"
    sn = "sn"
    so = "so"
    sq = "sq"
    sr = "sr"
    ss = "ss"
    st = "st"
    su = "su"
    sv = "sv"
    sw = "sw"
    ta = "ta"
    te = "te"  # codespell:ignore
    tg = "tg"
    th = "th"
    ti = "ti"
    tk = "tk"
    tl = "tl"
    tn = "tn"
    to = "to"
    tr = "tr"
    ts = "ts"
    tt = "tt"
    tw = "tw"
    ty = "ty"
    ug = "ug"
    uk = "uk"
    ur = "ur"
    uz = "uz"
    ve = "ve"
    vi = "vi"
    vo = "vo"
    wa = "wa"
    wo = "wo"
    xh = "xh"
    yi = "yi"
    yo = "yo"
    za = "za"
    zh = "zh"
    zu = "zu"


class AccessMode(Enum):
    access_mode_free = "access_mode-free"
    access_mode_free_conditionally = "access_mode-free_conditionally"
    access_mode_other = "access_mode-other"
    access_mode_paid = "access_mode-paid"
    access_mode_peer_reviewed = "access_mode-peer_reviewed"


class TargetUser(Enum):
    target_user_businesses = "target_user-businesses"
    target_user_funders = "target_user-funders"
    target_user_innovators = "target_user-innovators"
    target_user_other = "target_user-other"
    target_user_policy_makers = "target_user-policy_makers"
    target_user_providers = "target_user-providers"
    target_user_research_communities = "target_user-research_communities"
    target_user_research_groups = "target_user-research_groups"
    target_user_research_infrastructure_managers = (
        "target_user-research_infrastructure_managers"
    )
    target_user_research_managers = "target_user-research_managers"
    target_user_research_networks = "target_user-research_networks"
    target_user_research_organisations = "target_user-research_organisations"
    target_user_research_projects = "target_user-research_projects"
    target_user_researchers = "target_user-researchers"
    target_user_resource_managers = "target_user-resource_managers"
    target_user_resource_provider_managers = "target_user-resource_provider_managers"
    target_user_publishers = "target_user-publishers"
    target_user_students = "target_user-students"


class TRL(Enum):
    trl_1 = "trl-1"
    trl_2 = "trl-2"
    trl_3 = "trl-3"
    trl_4 = "trl-4"
    trl_5 = "trl-5"
    trl_6 = "trl-6"
    trl_7 = "trl-7"
    trl_8 = "trl-8"
    trl_9 = "trl-9"


class OrderType(Enum):
    order_type_fully_open_access = "order_type-fully_open_access"
    order_type_open_access = "order_type-open_access"
    order_type_order_required = "order_type-order_required"
    order_type_other = "order_type-other"


# As defined in https://docs.google.com/spreadsheets/d/11XrO7zH1zO0c9BvWaQd7eyFJFRvwrUm83t0oTAokODE/edit?gid=1823616558#gid=1823616558
class ServiceClassification(Enum):
    publishing_and_discovery = "Publishing & Discovery"
    research_assessment_and_monitoring = "Research Assessment & Monitoring"
    data_management_and_curation = "Data Management & Curation"
    data_processing_and_analysis = "Data Processing & Analysis"
    compute_services = "Compute Services"
    storage_services = "Storage Services"
    networking_services = "Networking Services"
    science_gateways = "Science Gateways"
    instrumentation_and_physical_resources = "Instrumentation & Physical Resources"
    research_support_and_collaboration = "Research Support & Collaboration"
    training_and_skills_development = "Training & Skills Development"
    infrastructure_operations_services = "Infrastructure Operations Services"
    persistent_identifiers = "Persistent Identifiers"
    other = "Other"


class CategoryId(Enum):
    category_access_physical_and_eInfrastructures_compute = (
        "category-access_physical_and_eInfrastructures-compute"
    )
    category_access_physical_and_eInfrastructures_data_storage = (
        "category-access_physical_and_eInfrastructures-data_storage"
    )
    category_access_physical_and_eInfrastructures_instrument_and_equipment = (
        "category-access_physical_and_eInfrastructures-instrument_and_equipment"
    )
    category_access_physical_and_eInfrastructures_material_storage = (
        "category-access_physical_and_eInfrastructures-material_storage"
    )
    category_access_physical_and_eInfrastructures_network = (
        "category-access_physical_and_eInfrastructures-network"
    )
    category_aggregators_and_integrators_aggregators_and_integrators = (
        "category-aggregators_and_integrators-aggregators_and_integrators"
    )
    category_other_other = "category-other-other"
    category_processing_and_analysis_data_analysis = (
        "category-processing_and_analysis-data_analysis"
    )
    category_processing_and_analysis_data_management = (
        "category-processing_and_analysis-data_management"
    )
    category_processing_and_analysis_measurement_and_materials_analysis = (
        "category-processing_and_analysis-measurement_and_materials_analysis"
    )
    category_security_and_operations_operations_and_infrastructure_management_services = "category-security_and_operations-operations_and_infrastructure_management_services"
    category_security_and_operations_security_and_identity = (
        "category-security_and_operations-security_and_identity"
    )
    category_sharing_and_discovery_applications = (
        "category-sharing_and_discovery-applications"
    )
    category_sharing_and_discovery_data = "category-sharing_and_discovery-data"
    category_sharing_and_discovery_development_resources = (
        "category-sharing_and_discovery-development_resources"
    )
    category_sharing_and_discovery_samples = "category-sharing_and_discovery-samples"
    category_sharing_and_discovery_scholarly_communication = (
        "category-sharing_and_discovery-scholarly_communication"
    )
    category_sharing_and_discovery_software = "category-sharing_and_discovery-software"
    category_training_and_support_consultancy_and_support = (
        "category-training_and_support-consultancy_and_support"
    )
    category_training_and_support_education_and_training = (
        "category-training_and_support-education_and_training"
    )


class SubcategoryId1(Enum):
    subcategory_access_physical_and_eInfrastructures_compute_container_management = (
        "subcategory-access_physical_and_eInfrastructures-compute-container_management"
    )
    subcategory_access_physical_and_eInfrastructures_compute_hpc_access = (
        "subcategory-access_physical_and_eInfrastructures-compute-hpc_access"
    )
    subcategory_access_physical_and_eInfrastructures_compute_interactive_notebooks = (
        "subcategory-access_physical_and_eInfrastructures-compute-interactive_notebooks"
    )
    subcategory_access_physical_and_eInfrastructures_compute_job_execution = (
        "subcategory-access_physical_and_eInfrastructures-compute-job_execution"
    )
    subcategory_access_physical_and_eInfrastructures_compute_orchestration = (
        "subcategory-access_physical_and_eInfrastructures-compute-orchestration"
    )
    subcategory_access_physical_and_eInfrastructures_compute_other = (
        "subcategory-access_physical_and_eInfrastructures-compute-other"
    )
    subcategory_access_physical_and_eInfrastructures_compute_serverless_applications_repository = "subcategory-access_physical_and_eInfrastructures-compute-serverless_applications_repository"
    subcategory_access_physical_and_eInfrastructures_compute_virtual_machine_management = "subcategory-access_physical_and_eInfrastructures-compute-virtual_machine_management"
    subcategory_access_physical_and_eInfrastructures_compute_workload_management = (
        "subcategory-access_physical_and_eInfrastructures-compute-workload_management"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_archive = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-archive"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_backup = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-backup"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_data = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-data"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_digital_preservation = "subcategory-access_physical_and_eInfrastructures-data_storage-digital_preservation"
    subcategory_access_physical_and_eInfrastructures_data_storage_disk = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-disk"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_file = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-file"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_online = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-online"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_other = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-other"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_queue = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-queue"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_recovery = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-recovery"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_replicated = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-replicated"
    )
    subcategory_access_physical_and_eInfrastructures_data_storage_synchronised = (
        "subcategory-access_physical_and_eInfrastructures-data_storage-synchronised"
    )
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_chromatographer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-chromatographer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_cytometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-cytometer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_digitisation_equipment = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-digitisation_equipment"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_geophysical = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-geophysical"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_laser = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-laser"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_microscopy = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-microscopy"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_monument_maintenance_equipment = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-monument_maintenance_equipment"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_other = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-other"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_radiation = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-radiation"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_spectrometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-spectrometer"
    subcategory_access_physical_and_eInfrastructures_instrument_and_equipment_spectrophotometer = "subcategory-access_physical_and_eInfrastructures-instrument_and_equipment-spectrophotometer"
    subcategory_access_physical_and_eInfrastructures_material_storage_archiving = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-archiving"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_assembly = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-assembly"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_disposal = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-disposal"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_fulfilment = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-fulfilment"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_other = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-other"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_packaging = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-packaging"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_preservation = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-preservation"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_quality_inspecting = "subcategory-access_physical_and_eInfrastructures-material_storage-quality_inspecting"
    subcategory_access_physical_and_eInfrastructures_material_storage_repository = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-repository"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_reworking = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-reworking"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_sorting = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-sorting"
    )
    subcategory_access_physical_and_eInfrastructures_material_storage_warehousing = (
        "subcategory-access_physical_and_eInfrastructures-material_storage-warehousing"
    )
    subcategory_access_physical_and_eInfrastructures_network_content_delivery_network = "subcategory-access_physical_and_eInfrastructures-network-content_delivery_network"
    subcategory_access_physical_and_eInfrastructures_network_direct_connect = (
        "subcategory-access_physical_and_eInfrastructures-network-direct_connect"
    )
    subcategory_access_physical_and_eInfrastructures_network_dns = (
        "subcategory-access_physical_and_eInfrastructures-network-dns"
    )
    subcategory_access_physical_and_eInfrastructures_network_exchange = (
        "subcategory-access_physical_and_eInfrastructures-network-exchange"
    )
    subcategory_access_physical_and_eInfrastructures_network_load_balancer = (
        "subcategory-access_physical_and_eInfrastructures-network-load_balancer"
    )
    subcategory_access_physical_and_eInfrastructures_network_other = (
        "subcategory-access_physical_and_eInfrastructures-network-other"
    )
    subcategory_access_physical_and_eInfrastructures_network_traffic_manager = (
        "subcategory-access_physical_and_eInfrastructures-network-traffic_manager"
    )
    subcategory_access_physical_and_eInfrastructures_network_virtual_nework = (
        "subcategory-access_physical_and_eInfrastructures-network-virtual_nework"
    )
    subcategory_access_physical_and_eInfrastructures_network_vpn_gateway = (
        "subcategory-access_physical_and_eInfrastructures-network-vpn_gateway"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_applications = "subcategory-aggregators_and_integrators-aggregators_and_integrators-applications"
    subcategory_aggregators_and_integrators_aggregators_and_integrators_data = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-data"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_other = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-other"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_services = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-services"
    )
    subcategory_aggregators_and_integrators_aggregators_and_integrators_software = (
        "subcategory-aggregators_and_integrators-aggregators_and_integrators-software"
    )
    subcategory_other_other_other = "subcategory-other-other-other"
    subcategory_processing_and_analysis_data_analysis_2d_3d_digitisation = (
        "subcategory-processing_and_analysis-data_analysis-2d_3d_digitisation"
    )
    subcategory_processing_and_analysis_data_analysis_artificial_intelligence = (
        "subcategory-processing_and_analysis-data_analysis-artificial_intelligence"
    )
    subcategory_processing_and_analysis_data_analysis_data_extrapolation = (
        "subcategory-processing_and_analysis-data_analysis-data_extrapolation"
    )
    subcategory_processing_and_analysis_data_analysis_forecast = (
        "subcategory-processing_and_analysis-data_analysis-forecast"
    )
    subcategory_processing_and_analysis_data_analysis_image_data_analysis = (
        "subcategory-processing_and_analysis-data_analysis-image_data_analysis"
    )
    subcategory_processing_and_analysis_data_analysis_machine_learning = (
        "subcategory-processing_and_analysis-data_analysis-machine_learning"
    )
    subcategory_processing_and_analysis_data_analysis_other = (
        "subcategory-processing_and_analysis-data_analysis-other"
    )
    subcategory_processing_and_analysis_data_analysis_quality_assesment = (
        "subcategory-processing_and_analysis-data_analysis-quality_assesment"
    )
    subcategory_processing_and_analysis_data_analysis_visualization = (
        "subcategory-processing_and_analysis-data_analysis-visualization"
    )
    subcategory_processing_and_analysis_data_analysis_workflows = (
        "subcategory-processing_and_analysis-data_analysis-workflows"
    )
    subcategory_processing_and_analysis_data_management_access = (
        "subcategory-processing_and_analysis-data_management-access"
    )
    subcategory_processing_and_analysis_data_management_annotation = (
        "subcategory-processing_and_analysis-data_management-annotation"
    )
    subcategory_processing_and_analysis_data_management_anonymisation = (
        "subcategory-processing_and_analysis-data_management-anonymisation"
    )
    subcategory_processing_and_analysis_data_management_brokering = (
        "subcategory-processing_and_analysis-data_management-brokering"
    )
    subcategory_processing_and_analysis_data_management_digitisation = (
        "subcategory-processing_and_analysis-data_management-digitisation"
    )
    subcategory_processing_and_analysis_data_management_discovery = (
        "subcategory-processing_and_analysis-data_management-discovery"
    )
    subcategory_processing_and_analysis_data_management_embargo = (
        "subcategory-processing_and_analysis-data_management-embargo"
    )
    subcategory_processing_and_analysis_data_management_interlinking = (
        "subcategory-processing_and_analysis-data_management-interlinking"
    )
    subcategory_processing_and_analysis_data_management_maintenance = (
        "subcategory-processing_and_analysis-data_management-maintenance"
    )
    subcategory_processing_and_analysis_data_management_mining = (
        "subcategory-processing_and_analysis-data_management-mining"
    )
    subcategory_processing_and_analysis_data_management_other = (
        "subcategory-processing_and_analysis-data_management-other"
    )
    subcategory_processing_and_analysis_data_management_persistent_identifier = (
        "subcategory-processing_and_analysis-data_management-persistent_identifier"
    )
    subcategory_processing_and_analysis_data_management_preservation = (
        "subcategory-processing_and_analysis-data_management-preservation"
    )
    subcategory_processing_and_analysis_data_management_publishing = (
        "subcategory-processing_and_analysis-data_management-publishing"
    )
    subcategory_processing_and_analysis_data_management_registration = (
        "subcategory-processing_and_analysis-data_management-registration"
    )
    subcategory_processing_and_analysis_data_management_transfer = (
        "subcategory-processing_and_analysis-data_management-transfer"
    )
    subcategory_processing_and_analysis_data_management_validation = (
        "subcategory-processing_and_analysis-data_management-validation"
    )
    subcategory_processing_and_analysis_measurement_and_materials_analysis_analysis = "subcategory-processing_and_analysis-measurement_and_materials_analysis-analysis"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_characterisation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-characterisation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_maintenance_and_modification = "subcategory-processing_and_analysis-measurement_and_materials_analysis-maintenance_and_modification"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_other = (
        "subcategory-processing_and_analysis-measurement_and_materials_analysis-other"
    )
    subcategory_processing_and_analysis_measurement_and_materials_analysis_production = "subcategory-processing_and_analysis-measurement_and_materials_analysis-production"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_testing_and_validation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-testing_and_validation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_validation = "subcategory-processing_and_analysis-measurement_and_materials_analysis-validation"
    subcategory_processing_and_analysis_measurement_and_materials_analysis_workflows = "subcategory-processing_and_analysis-measurement_and_materials_analysis-workflows"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_accounting = "subcategory-security_and_operations-operations_and_infrastructure_management_services-accounting"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_analysis = "subcategory-security_and_operations-operations_and_infrastructure_management_services-analysis"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_billing = "subcategory-security_and_operations-operations_and_infrastructure_management_services-billing"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_configuration = "subcategory-security_and_operations-operations_and_infrastructure_management_services-configuration"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_coordination = "subcategory-security_and_operations-operations_and_infrastructure_management_services-coordination"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_helpdesk = "subcategory-security_and_operations-operations_and_infrastructure_management_services-helpdesk"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_monitoring = "subcategory-security_and_operations-operations_and_infrastructure_management_services-monitoring"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_order_management = "subcategory-security_and_operations-operations_and_infrastructure_management_services-order_management"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_other = "subcategory-security_and_operations-operations_and_infrastructure_management_services-other"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_transportation = "subcategory-security_and_operations-operations_and_infrastructure_management_services-transportation"
    subcategory_security_and_operations_operations_and_infrastructure_management_services_utilities = "subcategory-security_and_operations-operations_and_infrastructure_management_services-utilities"
    subcategory_security_and_operations_security_and_identity_certification_authority = "subcategory-security_and_operations-security_and_identity-certification_authority"
    subcategory_security_and_operations_security_and_identity_coordination = (
        "subcategory-security_and_operations-security_and_identity-coordination"
    )
    subcategory_security_and_operations_security_and_identity_firewall = (
        "subcategory-security_and_operations-security_and_identity-firewall"
    )
    subcategory_security_and_operations_security_and_identity_group_management = (
        "subcategory-security_and_operations-security_and_identity-group_management"
    )
    subcategory_security_and_operations_security_and_identity_identity_and_access_management = "subcategory-security_and_operations-security_and_identity-identity_and_access_management"
    subcategory_security_and_operations_security_and_identity_other = (
        "subcategory-security_and_operations-security_and_identity-other"
    )
    subcategory_security_and_operations_security_and_identity_single_sign_on = (
        "subcategory-security_and_operations-security_and_identity-single_sign_on"
    )
    subcategory_security_and_operations_security_and_identity_threat_protection = (
        "subcategory-security_and_operations-security_and_identity-threat_protection"
    )
    subcategory_security_and_operations_security_and_identity_tools = (
        "subcategory-security_and_operations-security_and_identity-tools"
    )
    subcategory_security_and_operations_security_and_identity_user_authentication = (
        "subcategory-security_and_operations-security_and_identity-user_authentication"
    )
    subcategory_sharing_and_discovery_applications_applications_repository = (
        "subcategory-sharing_and_discovery-applications-applications_repository"
    )
    subcategory_sharing_and_discovery_applications_business = (
        "subcategory-sharing_and_discovery-applications-business"
    )
    subcategory_sharing_and_discovery_applications_collaboration = (
        "subcategory-sharing_and_discovery-applications-collaboration"
    )
    subcategory_sharing_and_discovery_applications_communication = (
        "subcategory-sharing_and_discovery-applications-communication"
    )
    subcategory_sharing_and_discovery_applications_education = (
        "subcategory-sharing_and_discovery-applications-education"
    )
    subcategory_sharing_and_discovery_applications_other = (
        "subcategory-sharing_and_discovery-applications-other"
    )
    subcategory_sharing_and_discovery_applications_productivity = (
        "subcategory-sharing_and_discovery-applications-productivity"
    )
    subcategory_sharing_and_discovery_applications_social_networking = (
        "subcategory-sharing_and_discovery-applications-social_networking"
    )
    subcategory_sharing_and_discovery_applications_utilities = (
        "subcategory-sharing_and_discovery-applications-utilities"
    )
    subcategory_sharing_and_discovery_data_clinical_trial_data = (
        "subcategory-sharing_and_discovery-data-clinical_trial_data"
    )
    subcategory_sharing_and_discovery_data_data_archives = (
        "subcategory-sharing_and_discovery-data-data_archives"
    )
    subcategory_sharing_and_discovery_data_epidemiological_data = (
        "subcategory-sharing_and_discovery-data-epidemiological_data"
    )
    subcategory_sharing_and_discovery_data_government_and_agency_data = (
        "subcategory-sharing_and_discovery-data-government_and_agency_data"
    )
    subcategory_sharing_and_discovery_data_metadata = (
        "subcategory-sharing_and_discovery-data-metadata"
    )
    subcategory_sharing_and_discovery_data_online_service_data = (
        "subcategory-sharing_and_discovery-data-online_service_data"
    )
    subcategory_sharing_and_discovery_data_other = (
        "subcategory-sharing_and_discovery-data-other"
    )
    subcategory_sharing_and_discovery_data_scientific_research_data = (
        "subcategory-sharing_and_discovery-data-scientific_research_data"
    )
    subcategory_sharing_and_discovery_data_statistical_data = (
        "subcategory-sharing_and_discovery-data-statistical_data"
    )
    subcategory_sharing_and_discovery_development_resources_apis_repository_gateway = "subcategory-sharing_and_discovery-development_resources-apis_repository_gateway"
    subcategory_sharing_and_discovery_development_resources_developer_tools = (
        "subcategory-sharing_and_discovery-development_resources-developer_tools"
    )
    subcategory_sharing_and_discovery_development_resources_other = (
        "subcategory-sharing_and_discovery-development_resources-other"
    )
    subcategory_sharing_and_discovery_development_resources_simulation_tools = (
        "subcategory-sharing_and_discovery-development_resources-simulation_tools"
    )
    subcategory_sharing_and_discovery_development_resources_software_development_kits = "subcategory-sharing_and_discovery-development_resources-software_development_kits"
    subcategory_sharing_and_discovery_development_resources_software_libraries = (
        "subcategory-sharing_and_discovery-development_resources-software_libraries"
    )
    subcategory_sharing_and_discovery_samples_biological_samples = (
        "subcategory-sharing_and_discovery-samples-biological_samples"
    )
    subcategory_sharing_and_discovery_samples_characterisation = (
        "subcategory-sharing_and_discovery-samples-characterisation"
    )
    subcategory_sharing_and_discovery_samples_chemical_compounds_library = (
        "subcategory-sharing_and_discovery-samples-chemical_compounds_library"
    )
    subcategory_sharing_and_discovery_samples_other = (
        "subcategory-sharing_and_discovery-samples-other"
    )
    subcategory_sharing_and_discovery_samples_preparation = (
        "subcategory-sharing_and_discovery-samples-preparation"
    )
    subcategory_sharing_and_discovery_scholarly_communication_analysis = (
        "subcategory-sharing_and_discovery-scholarly_communication-analysis"
    )
    subcategory_sharing_and_discovery_scholarly_communication_assessment = (
        "subcategory-sharing_and_discovery-scholarly_communication-assessment"
    )
    subcategory_sharing_and_discovery_scholarly_communication_discovery = (
        "subcategory-sharing_and_discovery-scholarly_communication-discovery"
    )
    subcategory_sharing_and_discovery_scholarly_communication_other = (
        "subcategory-sharing_and_discovery-scholarly_communication-other"
    )
    subcategory_sharing_and_discovery_scholarly_communication_outreach = (
        "subcategory-sharing_and_discovery-scholarly_communication-outreach"
    )
    subcategory_sharing_and_discovery_scholarly_communication_preparation = (
        "subcategory-sharing_and_discovery-scholarly_communication-preparation"
    )
    subcategory_sharing_and_discovery_scholarly_communication_publication = (
        "subcategory-sharing_and_discovery-scholarly_communication-publication"
    )
    subcategory_sharing_and_discovery_scholarly_communication_writing = (
        "subcategory-sharing_and_discovery-scholarly_communication-writing"
    )
    subcategory_sharing_and_discovery_software_libraries = (
        "subcategory-sharing_and_discovery-software-libraries"
    )
    subcategory_sharing_and_discovery_software_other = (
        "subcategory-sharing_and_discovery-software-other"
    )
    subcategory_sharing_and_discovery_software_platform = (
        "subcategory-sharing_and_discovery-software-platform"
    )
    subcategory_sharing_and_discovery_software_software_package = (
        "subcategory-sharing_and_discovery-software-software_package"
    )
    subcategory_sharing_and_discovery_software_software_repository = (
        "subcategory-sharing_and_discovery-software-software_repository"
    )
    subcategory_training_and_support_consultancy_and_support_application_optimisation = "subcategory-training_and_support-consultancy_and_support-application_optimisation"
    subcategory_training_and_support_consultancy_and_support_application_porting = (
        "subcategory-training_and_support-consultancy_and_support-application_porting"
    )
    subcategory_training_and_support_consultancy_and_support_application_scaling = (
        "subcategory-training_and_support-consultancy_and_support-application_scaling"
    )
    subcategory_training_and_support_consultancy_and_support_audit_and_assessment = (
        "subcategory-training_and_support-consultancy_and_support-audit_and_assessment"
    )
    subcategory_training_and_support_consultancy_and_support_benchmarking = (
        "subcategory-training_and_support-consultancy_and_support-benchmarking"
    )
    subcategory_training_and_support_consultancy_and_support_calibration = (
        "subcategory-training_and_support-consultancy_and_support-calibration"
    )
    subcategory_training_and_support_consultancy_and_support_certification = (
        "subcategory-training_and_support-consultancy_and_support-certification"
    )
    subcategory_training_and_support_consultancy_and_support_consulting = (
        "subcategory-training_and_support-consultancy_and_support-consulting"
    )
    subcategory_training_and_support_consultancy_and_support_methodology_development = "subcategory-training_and_support-consultancy_and_support-methodology_development"
    subcategory_training_and_support_consultancy_and_support_modeling_and_simulation = "subcategory-training_and_support-consultancy_and_support-modeling_and_simulation"
    subcategory_training_and_support_consultancy_and_support_other = (
        "subcategory-training_and_support-consultancy_and_support-other"
    )
    subcategory_training_and_support_consultancy_and_support_prototype_development = (
        "subcategory-training_and_support-consultancy_and_support-prototype_development"
    )
    subcategory_training_and_support_consultancy_and_support_software_development = (
        "subcategory-training_and_support-consultancy_and_support-software_development"
    )
    subcategory_training_and_support_consultancy_and_support_software_improvement = (
        "subcategory-training_and_support-consultancy_and_support-software_improvement"
    )
    subcategory_training_and_support_consultancy_and_support_technology_transfer = (
        "subcategory-training_and_support-consultancy_and_support-technology_transfer"
    )
    subcategory_training_and_support_consultancy_and_support_testing = (
        "subcategory-training_and_support-consultancy_and_support-testing"
    )
    subcategory_training_and_support_education_and_training_in_house_courses = (
        "subcategory-training_and_support-education_and_training-in_house_courses"
    )
    subcategory_training_and_support_education_and_training_online_courses = (
        "subcategory-training_and_support-education_and_training-online_courses"
    )
    subcategory_training_and_support_education_and_training_open_registration_courses = "subcategory-training_and_support-education_and_training-open_registration_courses"
    subcategory_training_and_support_education_and_training_other = (
        "subcategory-training_and_support-education_and_training-other"
    )
    subcategory_training_and_support_education_and_training_related_training = (
        "subcategory-training_and_support-education_and_training-related_training"
    )
    subcategory_training_and_support_education_and_training_required_training = (
        "subcategory-training_and_support-education_and_training-required_training"
    )
    subcategory_training_and_support_education_and_training_training_platform = (
        "subcategory-training_and_support-education_and_training-training_platform"
    )
    subcategory_training_and_support_education_and_training_training_tool = (
        "subcategory-training_and_support-education_and_training-training_tool"
    )


class SubcategoryId(RootModel[SubcategoryId1 | None]):
    root: SubcategoryId1 | None


class ScientificDomains(Enum):
    scientific_domain_agricultural_sciences = "scientific_domain-agricultural_sciences"
    scientific_domain_engineering_and_technology = (
        "scientific_domain-engineering_and_technology"
    )
    scientific_domain_generic = "scientific_domain-generic"
    scientific_domain_humanities = "scientific_domain-humanities"
    scientific_domain_medical_and_health_sciences = (
        "scientific_domain-medical_and_health_sciences"
    )
    scientific_domain_natural_sciences = "scientific_domain-natural_sciences"
    scientific_domain_other = "scientific_domain-other"
    scientific_domain_social_sciences = "scientific_domain-social_sciences"


class ScientificSubdomains(Enum):
    scientific_subdomain_agricultural_sciences_agricultural_biotechnology = (
        "scientific_subdomain-agricultural_sciences-agricultural_biotechnology"
    )
    scientific_subdomain_agricultural_sciences_agriculture_forestry_and_fisheries = (
        "scientific_subdomain-agricultural_sciences-agriculture_forestry_and_fisheries"
    )
    scientific_subdomain_agricultural_sciences_animal_and_dairy_sciences = (
        "scientific_subdomain-agricultural_sciences-animal_and_dairy_sciences"
    )
    scientific_subdomain_agricultural_sciences_other_agricultural_sciences = (
        "scientific_subdomain-agricultural_sciences-other_agricultural_sciences"
    )
    scientific_subdomain_agricultural_sciences_veterinary_sciences = (
        "scientific_subdomain-agricultural_sciences-veterinary_sciences"
    )
    scientific_subdomain_engineering_and_technology_chemical_engineering = (
        "scientific_subdomain-engineering_and_technology-chemical_engineering"
    )
    scientific_subdomain_engineering_and_technology_civil_engineering = (
        "scientific_subdomain-engineering_and_technology-civil_engineering"
    )
    scientific_subdomain_engineering_and_technology_electrical_electronic_and_information_engineering = "scientific_subdomain-engineering_and_technology-electrical_electronic_and_information_engineering"
    scientific_subdomain_engineering_and_technology_environmental_biotechnology = (
        "scientific_subdomain-engineering_and_technology-environmental_biotechnology"
    )
    scientific_subdomain_engineering_and_technology_environmental_engineering = (
        "scientific_subdomain-engineering_and_technology-environmental_engineering"
    )
    scientific_subdomain_engineering_and_technology_industrial_biotechnology = (
        "scientific_subdomain-engineering_and_technology-industrial_biotechnology"
    )
    scientific_subdomain_engineering_and_technology_materials_engineering = (
        "scientific_subdomain-engineering_and_technology-materials_engineering"
    )
    scientific_subdomain_engineering_and_technology_mechanical_engineering = (
        "scientific_subdomain-engineering_and_technology-mechanical_engineering"
    )
    scientific_subdomain_engineering_and_technology_medical_engineering = (
        "scientific_subdomain-engineering_and_technology-medical_engineering"
    )
    scientific_subdomain_engineering_and_technology_nanotechnology = (
        "scientific_subdomain-engineering_and_technology-nanotechnology"
    )
    scientific_subdomain_engineering_and_technology_other_engineering_and_technology_sciences = "scientific_subdomain-engineering_and_technology-other_engineering_and_technology_sciences"
    scientific_subdomain_generic_generic = "scientific_subdomain-generic-generic"
    scientific_subdomain_humanities_arts = "scientific_subdomain-humanities-arts"
    scientific_subdomain_humanities_history_and_archaeology = (
        "scientific_subdomain-humanities-history_and_archaeology"
    )
    scientific_subdomain_humanities_languages_and_literature = (
        "scientific_subdomain-humanities-languages_and_literature"
    )
    scientific_subdomain_humanities_other_humanities = (
        "scientific_subdomain-humanities-other_humanities"
    )
    scientific_subdomain_humanities_philosophy_ethics_and_religion = (
        "scientific_subdomain-humanities-philosophy_ethics_and_religion"
    )
    scientific_subdomain_medical_and_health_sciences_basic_medicine = (
        "scientific_subdomain-medical_and_health_sciences-basic_medicine"
    )
    scientific_subdomain_medical_and_health_sciences_clinical_medicine = (
        "scientific_subdomain-medical_and_health_sciences-clinical_medicine"
    )
    scientific_subdomain_medical_and_health_sciences_health_sciences = (
        "scientific_subdomain-medical_and_health_sciences-health_sciences"
    )
    scientific_subdomain_medical_and_health_sciences_medical_biotechnology = (
        "scientific_subdomain-medical_and_health_sciences-medical_biotechnology"
    )
    scientific_subdomain_medical_and_health_sciences_other_medical_sciences = (
        "scientific_subdomain-medical_and_health_sciences-other_medical_sciences"
    )
    scientific_subdomain_natural_sciences_biological_sciences = (
        "scientific_subdomain-natural_sciences-biological_sciences"
    )
    scientific_subdomain_natural_sciences_chemical_sciences = (
        "scientific_subdomain-natural_sciences-chemical_sciences"
    )
    scientific_subdomain_natural_sciences_computer_and_information_sciences = (
        "scientific_subdomain-natural_sciences-computer_and_information_sciences"
    )
    scientific_subdomain_natural_sciences_earth_and_related_environmental_sciences = (
        "scientific_subdomain-natural_sciences-earth_and_related_environmental_sciences"
    )
    scientific_subdomain_natural_sciences_mathematics = (
        "scientific_subdomain-natural_sciences-mathematics"
    )
    scientific_subdomain_natural_sciences_other_natural_sciences = (
        "scientific_subdomain-natural_sciences-other_natural_sciences"
    )
    scientific_subdomain_natural_sciences_physical_sciences = (
        "scientific_subdomain-natural_sciences-physical_sciences"
    )
    scientific_subdomain_other_other = "scientific_subdomain-other-other"
    scientific_subdomain_social_sciences_economics_and_business = (
        "scientific_subdomain-social_sciences-economics_and_business"
    )
    scientific_subdomain_social_sciences_educational_sciences = (
        "scientific_subdomain-social_sciences-educational_sciences"
    )
    scientific_subdomain_social_sciences_law = (
        "scientific_subdomain-social_sciences-law"
    )
    scientific_subdomain_social_sciences_media_and_communications = (
        "scientific_subdomain-social_sciences-media_and_communications"
    )
    scientific_subdomain_social_sciences_other_social_sciences = (
        "scientific_subdomain-social_sciences-other_social_sciences"
    )
    scientific_subdomain_social_sciences_political_sciences = (
        "scientific_subdomain-social_sciences-political_sciences"
    )
    scientific_subdomain_social_sciences_psychology = (
        "scientific_subdomain-social_sciences-psychology"
    )
    scientific_subdomain_social_sciences_social_and_economic_geography = (
        "scientific_subdomain-social_sciences-social_and_economic_geography"
    )
    scientific_subdomain_social_sciences_sociology = (
        "scientific_subdomain-social_sciences-sociology"
    )


class ResearchDomain(Enum):
    natural_sciences = "natural sciences"
    agricultural_sciences = "agricultural sciences"
    medical_and_health_sciences = "medical and health sciences"
    engineering_and_technology = "engineering and technology"
    social_sciences = "social sciences"
    humanities = "humanities"


class ResearchSubDomain(Enum):
    physical_sciences = "physical sciences"
    earth_and_related_environmental_sciences = (
        "earth and related environmental sciences"
    )
    chemical_sciences = "chemical sciences"
    computer_and_information_sciences = "computer and information sciences"
    biological_sciences = "biological sciences"
    mathematics = "mathematics"
    other_natural_sciences = "other natural sciences"
    agriculture_forestry_and_fisheries = "agriculture, forestry, and fisheries"
    animal_and_dairy_science = "animal and dairy science"
    agricultural_biotechnology = "agricultural biotechnology"
    other_agricultural_sciences = "other agricultural sciences"
    veterinary_sciences = "veterinary sciences"
    health_sciences = "health sciences"
    basic_medicine = "basic medicine"
    clinical_medicine = "clinical medicine"
    other_medical_sciences = "other medical sciences"
    medical_biotechnology = "medical biotechnology"
    materials_engineering = "materials engineering"
    civil_engineering = "civil engineering"
    electrical_engineering_electronic_engineering_information_engineering = (
        "electrical engineering, electronic engineering, information engineering"
    )
    environmental_engineering = "environmental engineering"
    other_engineering_and_technologies = "other engineering and technologies"
    industrial_biotechnology = "industrial biotechnology"
    mechanical_engineering = "mechanical engineering"
    nanotechnology = "nanotechnology"
    chemical_engineering = "chemical engineering"
    environmental_biotechnology = "environmental biotechnology"
    medical_engineering = "medical engineering"
    sociology = "sociology"
    economics_and_business = "economics and business"
    social_geography = "social geography"
    law = "law"
    political_sciences = "political sciences"
    psychology = "psychology"
    educational_sciences = "educational sciences"
    other_social_sciences = "other social sciences"
    media_and_communications = "media and communications"
    languages_and_literature = "languages and literature"
    history_and_archaeology = "history and archaeology"
    arts = "arts"
    philosophy_ethics_and_religion = "philosophy, ethics and religion"
    other_humanities = "other humanities"


# this may be helpful in the future, not sure how the research domains will be
# handled by the API
RESEARCH_DOMAINS = [
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/3d76a7f4-5a16-411e-ae44-7b712d5222ee",
        "name": "natural sciences",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/d3b09b78-ac5c-4fc3-b58a-9573daf0e304",
                "name": "physical sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/4a8788fc-4172-461c-ae94-40be4f39043f",
                "name": "earth and related environmental sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/bce870dd-43f3-4656-8866-d76b0d71f5b8",
                "name": "chemical sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/e437ed99-4a4e-4fb3-af7e-fae6a2c2a800",
                "name": "computer and information sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/803cff73-504b-41ae-9873-1836c76c15d1",
                "name": "biological sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/5ac3ab8e-7d50-4091-94e2-0eec71c915db",
                "name": "mathematics",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/e5178751-bb89-45c6-802b-2d2374b3ecc3",
                "name": "other natural sciences",
            },
        ],
    },
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/9b9abbee-82f5-4766-bd4d-feb73cf06573",
        "name": "agricultural sciences",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/4df60e5a-a143-45d2-b1a6-c2dcb31d977a",
                "name": "agriculture, forestry, and fisheries",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/b33c5338-c5bb-4026-8b86-7e2ff7cd2e3c",
                "name": "animal and dairy science",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/1d8b779c-f72c-40fe-a8b9-22608c4e9df4",
                "name": "agricultural biotechnology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/fba9976f-0a7e-410c-8fce-3a6cef46f5e1",
                "name": "other agricultural sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/55e533c2-cad7-45bc-a66f-e813cda04e70",
                "name": "veterinary sciences",
            },
        ],
    },
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/9e8e1abb-1a14-40ef-9658-782092fa5cf6",
        "name": "medical and health sciences",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/34b9c059-9e6c-4ec1-8a96-845c95c1a978",
                "name": "health sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/5c631d7c-2a8c-40b4-9ba9-71121e2d5e63",
                "name": "basic medicine",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/a348fcd2-3bdd-46f9-aa2c-a91301f1e12e",
                "name": "clinical medicine",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/a357cf4d-48e6-4d5d-b8bf-3e39cbbbe713",
                "name": "other medical sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/495b214f-06c8-45b9-a5d2-64e2df5dc2e3",
                "name": "medical biotechnology",
            },
        ],
    },
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/64605fff-1946-4fd4-b021-e2e83b71dcac",
        "name": "engineering and technology",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/dc9a4100-9eb3-4956-8fd8-b67ea07a70ad",
                "name": "materials engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/26770c2b-64ce-4611-896f-cdefb4893317",
                "name": "civil engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/325a846e-9c47-4aca-9358-5c8facd2e812",
                "name": "electrical engineering, electronic engineering, "
                "information engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/531bd18a-eedd-4345-8b2f-5464f96615f8",
                "name": "environmental engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/14e75836-6f05-46f9-9c82-ca12468b0452",
                "name": "other engineering and technologies",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/12df4518-adab-4191-a79f-74eb18ad1688",
                "name": "industrial biotechnology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/ea994073-d367-4ed7-9df3-4477a9c6cf6f",
                "name": "mechanical engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/739766f0-539e-4fba-8144-9249bb38719a",
                "name": "nanotechnology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/10352c4c-328e-4dac-a89c-44b6be1420e9",
                "name": "chemical engineering",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/776bf529-b4bb-458b-ad4f-50b327a822ce",
                "name": "environmental biotechnology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/742439ad-5d62-4e2d-bd77-0eb7caaa75f4",
                "name": "medical engineering",
            },
        ],
    },
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/12c980a5-034f-4cd5-8ce7-fcfe109c675c",
        "name": "social sciences",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/839b7158-09d9-4799-aacc-bb07d00c1668",
                "name": "sociology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/052bc92d-760c-43ab-958e-2330c72a4212",
                "name": "economics and business",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/8614801c-e2ae-4e99-93b0-cfecb09c4f35",
                "name": "social geography",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/77030c6f-37d5-46d0-961c-b2a053ecb8d7",
                "name": "law",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/f8714203-d97f-4852-b051-3b63b2795faa",
                "name": "political sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/5c66325e-b247-4e52-92ec-544ae4d061cc",
                "name": "psychology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/734e0a2e-5a5f-4bee-aff1-39389370e524",
                "name": "educational sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/0bf709d0-834b-4448-a89c-7fb04cece64a",
                "name": "other social sciences",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/8d3657d8-563a-47fb-a5c2-5592b08365b5",
                "name": "media and communications",
            },
        ],
    },
    {
        "id": "http://data.europa.eu/8mn/euroscivoc/7a2dcf7b-2c20-468a-a81c-76d67c14de31",
        "name": "humanities",
        "subdomains": [
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/1ad04442-4f97-4a5e-aba8-4fc2889faeca",
                "name": "languages and literature",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/de62b610-a9d3-430b-92ff-366f28f7b1c7",
                "name": "history and archaeology",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/a55114ca-1ad7-4c52-a261-d753fbeb3529",
                "name": "arts",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/866c484a-44d8-4fde-b54f-3b1d9f8ca612",
                "name": "philosophy, ethics and religion",
            },
            {
                "id": "http://data.europa.eu/8mn/euroscivoc/e2120c91-f57d-4f96-8992-59c109634f1c",
                "name": "other humanities",
            },
        ],
    },
]


class AlternativeIdentifier(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str = Field(
        min_length=1, description="Type of the identifier (e.g. doi, hdl)."
    )
    value: str = Field(min_length=1, description="Identifier value.")


class ScientificDomainEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scientificDomain: ScientificDomains
    scientificSubdomain: ScientificSubdomains | None = None


class ServiceCategoryEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    category: CategoryId
    subcategory: SubcategoryId | None = None


def enum_list_value_by_name(value: Any, enum_type: Any) -> Any:
    if not isinstance(value, list):
        return value
    else:
        return [getattr(enum_type, v, v) for v in value]


class Service(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        use_enum_values=True,
    )
    id: str = Field(..., description="Service identifier (same as service bundle ID).")
    alternativeIdentifiers: list[AlternativeIdentifier] = Field(
        None, description="Alternative identifiers for the service.", min_length=0
    )
    abbreviation: str | None = Field(
        None, description="Abbreviation of the service name.", min_length=1
    )
    name: str = Field(..., description="Full name of the service.", min_length=1)
    webpage: AnyUrl = Field(..., description="URL of the service webpage.")
    description: str = Field(
        ..., description="Detailed description of the service.", min_length=1
    )
    tagline: str | None = Field(
        description="Short tagline summarising the service.", min_length=1
    )
    logo: AnyUrl | None = Field(None, description="URL of the service logo.")
    scientificDomains: list[ScientificDomainEntry] = Field(
        ..., description="Scientific domains applicable to the service.", min_length=1
    )
    categories: list[ServiceCategoryEntry] = Field(
        ..., description="Service categories.", min_length=1
    )
    classification: Annotated[
        list[ServiceClassification] | None, Field(description="Service classification.")
    ] = None
    targetUsers: list[TargetUser] = Field(
        ..., description="Intended target users.", min_length=1
    )
    accessModes: list[AccessMode] | None = Field(
        None, description="Access mode provided by the service.", min_length=1
    )
    tags: list[str] | None = Field(
        description="Free-text tags for the service.", min_length=0
    )
    languageAvailabilities: list[LanguageCode] = Field(
        ...,
        description="Languages available for the service (ISO 639-1 codes).",
        min_length=1,
    )
    helpdeskEmail: EmailStr | None = Field(None, description="Helpdesk contact email.")
    securityContactEmail: EmailStr | None = Field(
        None, description="Security contact email."
    )
    trl: TRL = Field(..., description="Technology readiness level.")
    userManual: AnyUrl | None = Field(None, description="URL for the user manual.")
    termsOfUse: AnyUrl | None = Field(None, description="URL for the terms of use.")
    privacyPolicy: AnyUrl | None = Field(
        None, description="URL for the privacy policy."
    )
    accessPolicy: AnyUrl | None = Field(None, description="URL for the access policy.")
    orderType: OrderType = Field(..., description="Ordering modality for the service.")

    @field_validator("classification", mode="before")
    @classmethod
    def validate_enum_list(cls, value: Any) -> Any:
        return enum_list_value_by_name(value, ServiceClassification)


class EOSCServiceBundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ..., description="Unique identifier for the service bundle.", min_length=1
    )
    service: Service = Field(..., description="Metadata of the catalogued service.")
