---
name: Build and push containers

on:
  release:
    types: [released]
  pull_request:
  push:

permissions: read-all

jobs:
  builder:
    name: Build and push images
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          # This is needed for PBR get the right version
          fetch-depth: 0
          persist-credentials: false
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: registry.egi.eu/cloud.egi.eu/eosc-service-catalogue
          tags: |
            type=sha
            type=pep440,pattern={{version}}
            latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      - name: Login to Registry 
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: registry.egi.eu
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        if: github.event_name == 'release'
      - name: Build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          context: .
      - name: Get helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2
        if: github.event_name == 'release'
      - name: deploy 
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          IMAGE_PULL_CREDENTIALS: ${{ secrets.IMAGE_PULL_CREDENTIALS }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ./kubeconfig
          export KUBECONFIG="./kubeconfig"
          echo "$IMAGE_PULL_CREDENTIALS" > config.yaml
          helm upgrade --install eosc-svc ./chart/eosc-service-registry/ -n egi-ops-portal-ns \
            -f config.yaml --set image.tag="sha-$(git rev-parse --short HEAD)"
        if: github.event_name == 'release'
