---
name: Deploy

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  builder:
    name: Deploy to k8s 
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Get helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2
        id: install
      - name: deploy 
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          IMAGE_PULL_CREDENTIALS: ${{ secrets.IMAGE_PULL_CREDENTIALS }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          echo "$IMAGE_PULL_CREDENTIALS" > config.yaml
          helm upgrade --install eosc-svc ./chart/eosc-service-registry/ -n egi-ops-portal-ns \
            -f config.yaml
